Make sure multicamera render uses correct camera
ynput/ayon-3dsmax pull request #13
Opened 2024-09-17 13:54 UTC by moonyuet

## Changelog Description
This PR is to fix the bug of using same camera across the scenes when multicamera option is enabled.

## Additional info
n/a

## Testing notes:

1. Create Render Instance with multicamera option enabled
2. Publish
3. Check your published renders are with different cameras.

2024-09-23 13:36 UTC, LiborBatek requested changes
When submitting mutli camera render I got 2 sets of renders for camera1 and camera2 but the issue here is they arent animated but still.

Not sure why, but the camera moves are missing completeley. There is just correct poin of view for both.

No errors shown during Publishing and rendering on deadline....all good on this front.

2024-10-07 12:10 UTC, moonyuet commented
@LiborBatek Any update on this? It would be great to know which version of 3dsMax if it is still failing on the test. (Or you can send me the scenes)
I personally tested in Max 2024, 2023, it is actually working fine. 
Maybe you should check whether the camera animation is set within the frame range which is published for rendering?

2024-10-07 15:37 UTC, moonyuet commented
> Currently I cant publish multicam render due to error during `render` publishing
> 
> ![image](https://private-user-images.githubusercontent.com/112623825/374233158-e120cd78-48d5-4fc2-b729-9cdf174474fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTUyMDMsIm5iZiI6MTcyODMxNDkwMywicGF0aCI6Ii8xMTI2MjM4MjUvMzc0MjMzMTU4LWUxMjBjZDc4LTQ4ZDUtNGZjMi1iNzI5LTljZGYxNzQ0NzRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNTI4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWRiNDA0MmQxNmY4ZDU0YjY5YTM2Zjg5MTgzYTZlNzA2NmUxMWM4YmM2ZWFmMDZiMGJhODliYzM1ZWQyODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xl0FmHsrTRPPOo7tbq11uCBJ4FGfk8b2wAIcl5KN9Gk)
> 
> Also enclosing full JSON publish report for inspection: [publish-report-241007-17-26.json.txt](https://github.com/user-attachments/files/17280966/publish-report-241007-17-26.json.txt)

@LiborBatek can you run the latest develop and try again? Just want to make sure it is not different issue from the change.

2024-10-08 08:31 UTC, moonyuet commented
> Currently I cant publish multicam render due to error during `render` publishing
> 
> ![image](https://private-user-images.githubusercontent.com/112623825/374233158-e120cd78-48d5-4fc2-b729-9cdf174474fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzY1MzgsIm5iZiI6MTcyODM3NjIzOCwicGF0aCI6Ii8xMTI2MjM4MjUvMzc0MjMzMTU4LWUxMjBjZDc4LTQ4ZDUtNGZjMi1iNzI5LTljZGYxNzQ0NzRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmI4ZmVkZDdmOTA4ZjY5YTRjOTU5OTYzYmRjYmEwMDMzZjM2Y2JmMzk3YjE2NDBkNzk1ZTNmYTExN2FjZWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qCBXkNEmUhSNTukFv0fYzom7cgo0XTeIssAp9hDG1yg)
> 
> Also enclosing full JSON publish report for inspection: [publish-report-241007-17-26.json.txt](https://github.com/user-attachments/files/17280966/publish-report-241007-17-26.json.txt)

@LiborBatek I cleaned up the code a little bit. can you test again?

2024-10-08 08:43 UTC, LiborBatek requested changes
Still no luck...

```
INFO: Using script file: C:\Users\lbate\AppData\Local\Temp\tmprm9madvl\extract_scene_files.py
DEBUG: Checking the scene files existing
ERROR: Camera scene files not existed yet!
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\max_0.2.4-dev.1\ayon_max\plugins\publish\save_scenes_for_cameras.py", line 106, in process
    raise RuntimeError("MaxBatch.exe doesn't run as expected")
RuntimeError: MaxBatch.exe doesn't run as expected
```

2024-10-08 08:49 UTC, BigRoy commented
Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?

2024-10-08 08:52 UTC, moonyuet commented
> Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?



> Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?
> 
> We don't need separate scene files - we just need the 3DsMax command line / renderer to know which camera to render, which is something Deadline has solved for ages - no?
> 
> I don't understand why we need separate max files.

We already set the cameras accordingly in the Plugin Info. 
![image](https://github.com/user-attachments/assets/0fc2ee89-7bad-483c-ad82-42a5d73041e8)
![image](https://github.com/user-attachments/assets/04743606-7b2f-499e-9bf8-b7dc0237f94b)

2024-10-08 08:56 UTC, BigRoy commented
> > Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?
> 
> > Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?
> > We don't need separate scene files - we just need the 3DsMax command line / renderer to know which camera to render, which is something Deadline has solved for ages - no?
> > I don't understand why we need separate max files.
> 
> We already set the cameras accordingly in the Plugin Info. ![image](https://private-user-images.githubusercontent.com/64118225/374483387-0fc2ee89-7bad-483c-ad82-42a5d73041e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc4NjgsIm5iZiI6MTcyODM3NzU2OCwicGF0aCI6Ii82NDExODIyNS8zNzQ0ODMzODctMGZjMmVlODktN2JhZC00ODNjLWFkODItNDJhNWQ3MzA0MWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4NTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZjQ4NTZjNTA2MjhlNzViN2Y4ODlkMTc1OTliYzYxZDViMTM4YjM0ZTg5ZDg0ZGM5Nzk5Y2EwNjlhZDVkMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZhAxPV-Sb-7-yti_Tkm4s1hsg2SwcwNmraXGiK2f00) ![image](https://private-user-images.githubusercontent.com/64118225/374483486-04743606-7b2f-499e-9bf8-b7dc0237f94b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc4NjgsIm5iZiI6MTcyODM3NzU2OCwicGF0aCI6Ii82NDExODIyNS8zNzQ0ODM0ODYtMDQ3NDM2MDYtN2IyZi00OTllLTliZjgtYjdkYzAyMzdmOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4NTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NzBjYTFmZTJlYTYzYWM2MzhmMzI3ZDA4NjkxYjMyMTMxZjkxZDk0NjJjNzcyMDdiMWY0ZDMwNmE2NDU4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r4s8CnhnoXwg8ZLUMCt5AxJUwikC9OW3bdp-nkVrtRc)

I mean - even in that submission I'm already seeing separate source `.max` files being used - that should be completely redundant because Deadline is capable of managing that just fine?

Could you share the full Deadline log?

It should trigger this code:
```python
        # Now load the max scene file.
        self.Plugin.LogInfo("Loading 3dsmax scene file")
        message = "StartJob,\"" + self.MaxFilename.replace("\\", "/") + "\",\"" + self.Camera + "\""
        self.MaxSocket.Send(message)
```

Which should send the `StartJob` command to max to render that particular camera as specified in the Plugin Info.
Also that `Camera0` and `Camera1` should not be submitted along? I don't see that as possible option for the plugin for 3Dsmax submitter?

2024-10-08 09:08 UTC, moonyuet commented
> Sorry - are we trying to fix this for Deadline jobs? Why are we **not** just passing `Camera` key-value to the Deadline `PluginInfo` on submission? Deadline has this solved a long time already?
> 
> We don't need separate scene files - we just need the 3DsMax command line / renderer to know which camera to render, which is something Deadline has solved for ages - no?
> 
> I don't understand why we need separate max files.
> 
> If we - for whatever reason _must_ change the render token of where it renders to because 3dsMax does not support a 'dynamic template key' like e.g. `<Camera>` in the render path then the solution could be to also pass `RenderOutput` key-value to the PluginInfo?

We have tried to do it with the single scene files (we developed this with Max 2023) and try the similar method of using tokens(batch render manager) to add the render queue by view and we can do the submission by views instead of by scene. But this may need lots of work for that.
We can put it into backlog, but it definitely needs some brainstorming and testing of how it should go for the farm submission.

2024-10-08 09:40 UTC, BigRoy commented
> We have tried to do it with the single scene files (we developed this with Max 2023) and try the similar method of using tokens(batch render manager) to add the render queue by view and we can do the submission by views instead of by scene. But this may need lots of work for that.
> We can put it into backlog, but it definitely needs some brainstorming and testing of how it should go for the farm submission.

Thanks - got to love bugs. Let's put that in backlog after yes - we should really try and avoid the need for these 'hacky' workarounds.

2024-10-08 14:13 UTC, LiborBatek requested changes
I have made new test round but still behaves the same wrong way...the error is exactly the same...so no change at all.

note:just for curiousity I have used also different ayon-deadline version 0.2.4 instead of 0.3.0 but this didnt make any change at all aka results been the same

2024-10-08 14:16 UTC, moonyuet commented
> I have made new test round but still behaves the same wrong way...the error is exactly the same...so no change at all.
> 
> note:just for curiousity I have used also different ayon-deadline version 0.2.4 instead of 0.3.0 but this didnt make any change at all aka results been the same

it's nothing wrong with the deadline addon, it hits error during we run the subprocess to save the files

2024-10-14 12:41 UTC, LiborBatek requested changes
Im still unable to ```publish``` render, enclosing full JSON log...

[3dsmax_publish-report-241014-14-37.json.txt](https://github.com/user-attachments/files/17364105/3dsmax_publish-report-241014-14-37.json.txt)

2024-10-17 13:00 UTC, LiborBatek commented
still failing on me... here is the publish report for your inspection

[3dsmax_publish-report-241017-14-56.json.txt](https://github.com/user-attachments/files/17412798/3dsmax_publish-report-241017-14-56.json.txt)

2024-10-17 13:22 UTC, BigRoy commented on client/ayon_max/plugins/publish/save_scenes_for_cameras.py
> +                            "-sceneFile", current_filepath])
Let's connect the the plug-in's logger.
```suggestion
                            "-sceneFile", current_filepath],
                            logger=self.log)
```

2024-10-17 13:22 UTC, BigRoy commented on client/ayon_max/plugins/publish/save_scenes_for_cameras.py
>              if not os.path.exists(camera_scene):
Can you add in the log message here the `{camera_scene}` variable so we report WHICH file is actually missing. That will make the log much more useful.

2024-10-17 13:22 UTC, BigRoy commented on client/ayon_max/plugins/publish/save_scenes_for_cameras.py
>              if not os.path.exists(camera_scene):
Also, before raising the `MaxBatch.exe` error it'd be great to debug log the contents of the script it would have been running? Also making the logs more useful.

So add something along the lines of:
```python
full_script = "\n".join(scripts)
self.log.debug(f"Failed running script {tmp_script_path}:\n{full_script }")
```

2024-10-17 15:11 UTC, LiborBatek commented
After those commits it still fails with following error:

```
ERROR:pyblish.plugin:Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "c:\Work\REPO\ayon-3dsmax\client\ayon_max\plugins\publish\save_scenes_for_cameras.py", line 102, in process
    run_subprocess([maxbatch_exe, tmp_script_path,
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\execute.py", line 167, in run_subprocess
    raise RuntimeError(exc_msg)
RuntimeError: Executing arguments was not successful: "(['C:\\Program Files\\Autodesk\\3ds Max 2024\\3dsmaxbatch.exe', 'C:/Users/lbate/AppData/Local/Temp/tmpgg_8z7zt/extract_scene_files.py', '-sceneFile', 'C:/projects/Ayon_Tests/max/max_shot/max_sh030/work/lighting/ATS_max_sh030_lighting_v007_CleanSlate.max'],)"

Output:
1Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\window.py", line 699, in _on_tab_change
    self._update_publish_details_widget()
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\window.py", line 658, in _update_publish_details_widget
    self._publish_details_widget.set_report_data(report_data)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\publish_report_viewer\widgets.py", line 857, in set_report_data
    self.set_report(report)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\publish_report_viewer\widgets.py", line 866, in set_report
    self._logs_text_widget.set_report(report)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\publish_report_viewer\widgets.py", line 320, in set_report
    self._update_logs()
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\publish_report_viewer\widgets.py", line 355, in _update_logs
    self._set_logs(filtered_logs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\publisher\publish_report_viewer\widgets.py", line 375, in _set_logs
    self._output_widget.setPlainText(text)
ValueError: embedded null character
```

2024-10-17 15:13 UTC, antirotor commented
I think there is maybe something wrong with your setup. I was able to submit it without issues, just waiting for the renders to finish

2024-10-17 15:18 UTC, antirotor approved these changes
Just tested it in max 2024 in simple setup - publishing takes some time but it works. Rendering is producing expected results that are then correctly published.

2024-10-17 15:23 UTC, antirotor requested changes
Oh I see it now, it is in the paths! Libor's issue is the camera naming:

It is trying to save file `ATS_max_sh030_lighting_v007_CleanSlate_cameraMain_01_:Camera1.max`
 and that won't work. We need to fix names for the scene.

or.... is it because of the referenced in cameras?

2024-10-17 16:04 UTC, moonyuet commented
> Oh I see it now, it is in the paths! Libor's issue is the camera naming:
> 
> It is trying to save file `ATS_max_sh030_lighting_v007_CleanSlate_cameraMain_01_:Camera1.max` and that won't work. We need to fix names for the scene.
> 
> or.... is it because of the referenced in cameras?

yes, it is probably a long fix. as it is also affecting the collector.

2024-10-18 05:05 UTC, moonyuet commented
@antirotor @LiborBatek I have implemented the changes to deal with the special characters along with the implementation of the small changes in deadline repos for 3dsamx farm submission https://github.com/ynput/ayon-deadline/pull/47. Please test this PR along with the PR lasted in the deadline repo.

2024-10-18 13:10 UTC, LiborBatek approved these changes
Once using the accompanying PR for Deadline all working smooth and nicely!

Render job successfully done and publish job also...

Resulting into 2 rendered sequences for both cameras! All good!

![image](https://github.com/user-attachments/assets/a253cdf9-f1ef-4f52-94d6-a36b853fe79e)

2024-10-21 09:18 UTC, BigRoy commented on client/ayon_max/plugins/publish/collect_render.py
> +        self.log.debug(instance.data["expectedFiles"])
```suggestion
```

2024-10-21 09:25 UTC, merged